const championSeedData = [
  { name: "Aatrox", archetype: "juggernaut", lanes: ["Baron"], roles: ["Fighter", "Tank"], damageType: "AD", difficulty: "Medium", tags: ["engage", "sustain"] },
  { name: "Ahri", archetype: "burstMage", lanes: ["Mid"], roles: ["Mage", "Assassin"], damageType: "AP", difficulty: "Medium", tags: ["mobility", "pick"] },
  { name: "Akali", archetype: "assassin", lanes: ["Mid", "Baron"], roles: ["Assassin"], damageType: "Mixed", difficulty: "Hard", tags: ["mobility"] },
  { name: "Akshan", archetype: "marksmanAssassin", lanes: ["Mid", "Dragon"], roles: ["Marksman", "Assassin"], damageType: "AD", difficulty: "Hard", tags: ["mobility", "pick"] },
  { name: "Alistar", archetype: "warden", lanes: ["Support"], roles: ["Tank", "Support"], damageType: "AP", difficulty: "Easy", tags: ["engage", "peel", "cc"] },
  { name: "Ambessa", archetype: "diver", lanes: ["Baron", "Jungle"], roles: ["Fighter"], damageType: "AD", difficulty: "Hard", tags: ["mobility", "burst"] },
  { name: "Amumu", archetype: "warden", lanes: ["Jungle", "Support"], roles: ["Tank"], damageType: "AP", difficulty: "Easy", tags: ["engage", "cc"] },
  { name: "Annie", archetype: "burstMage", lanes: ["Mid", "Support"], roles: ["Mage"], damageType: "AP", difficulty: "Easy", tags: ["pick", "cc"] },
  { name: "Ashe", archetype: "utilityMarksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Easy", tags: ["poke", "cc"] },
  { name: "Aurelion Sol", archetype: "battlemage", lanes: ["Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Hard", tags: ["scaling", "zone"] },
  { name: "Aurora", archetype: "burstMage", lanes: ["Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["mobility", "pick"] },
  { name: "Bard", archetype: "catcher", lanes: ["Support"], roles: ["Support", "Catcher"], damageType: "AP", difficulty: "Hard", tags: ["pick", "roam"] },
  { name: "Blitzcrank", archetype: "catcher", lanes: ["Support"], roles: ["Tank", "Support"], damageType: "AP", difficulty: "Easy", tags: ["pick", "engage"] },
  { name: "Brand", archetype: "battlemage", lanes: ["Mid", "Support"], roles: ["Mage"], damageType: "AP", difficulty: "Easy", tags: ["poke", "antiTank"] },
  { name: "Braum", archetype: "guardian", lanes: ["Support"], roles: ["Tank", "Support"], damageType: "AP", difficulty: "Easy", tags: ["peel", "frontline", "cc"] },
  { name: "Caitlyn", archetype: "marksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Easy", tags: ["poke", "range"] },
  { name: "Camille", archetype: "diver", lanes: ["Baron", "Jungle"], roles: ["Fighter"], damageType: "AD", difficulty: "Hard", tags: ["pick", "mobility"] },
  { name: "Corki", archetype: "artillery", lanes: ["Mid", "Dragon"], roles: ["Marksman", "Mage"], damageType: "Mixed", difficulty: "Medium", tags: ["poke", "scaling"] },
  { name: "Darius", archetype: "juggernaut", lanes: ["Baron"], roles: ["Fighter"], damageType: "AD", difficulty: "Easy", tags: ["frontline", "antiMelee"] },
  { name: "Diana", archetype: "diver", lanes: ["Mid", "Jungle"], roles: ["Fighter", "Mage"], damageType: "AP", difficulty: "Medium", tags: ["engage", "burst"] },
  { name: "Dr. Mundo", archetype: "juggernaut", lanes: ["Baron", "Jungle"], roles: ["Tank", "Fighter"], damageType: "AD", difficulty: "Easy", tags: ["frontline", "sustain"] },
  { name: "Draven", archetype: "marksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Hard", tags: ["burst", "laneBully"] },
  { name: "Ekko", archetype: "assassin", lanes: ["Mid", "Jungle"], roles: ["Assassin", "Mage"], damageType: "AP", difficulty: "Hard", tags: ["mobility", "burst"] },
  { name: "Evelynn", archetype: "assassin", lanes: ["Jungle"], roles: ["Assassin"], damageType: "AP", difficulty: "Hard", tags: ["pick", "burst"] },
  { name: "Ezreal", archetype: "pokeMarksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "Mixed", difficulty: "Medium", tags: ["poke", "mobility"] },
  { name: "Fiddlesticks", archetype: "battlemage", lanes: ["Jungle", "Support"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["engage", "zone", "sustain"] },
  { name: "Fiora", archetype: "skirmisher", lanes: ["Baron"], roles: ["Fighter"], damageType: "AD", difficulty: "Hard", tags: ["duelist", "splitpush"] },
  { name: "Fizz", archetype: "assassin", lanes: ["Mid"], roles: ["Assassin", "Mage"], damageType: "AP", difficulty: "Medium", tags: ["burst", "mobility"] },
  { name: "Galio", archetype: "guardian", lanes: ["Mid", "Support"], roles: ["Tank", "Mage"], damageType: "AP", difficulty: "Easy", tags: ["engage", "peel", "antiMagic"] },
  { name: "Garen", archetype: "juggernaut", lanes: ["Baron"], roles: ["Fighter"], damageType: "AD", difficulty: "Easy", tags: ["frontline", "sustain"] },
  { name: "Gnar", archetype: "skirmisher", lanes: ["Baron"], roles: ["Fighter", "Tank"], damageType: "AD", difficulty: "Hard", tags: ["poke", "engage"] },
  { name: "Gragas", archetype: "battlemage", lanes: ["Baron", "Jungle", "Mid"], roles: ["Tank", "Mage"], damageType: "AP", difficulty: "Medium", tags: ["engage", "peel"] },
  { name: "Graves", archetype: "marksmanFighter", lanes: ["Jungle"], roles: ["Marksman", "Fighter"], damageType: "AD", difficulty: "Medium", tags: ["burst", "durable"] },
  { name: "Gwen", archetype: "skirmisher", lanes: ["Baron", "Jungle"], roles: ["Fighter"], damageType: "AP", difficulty: "Medium", tags: ["antiTank", "scaling"] },
  { name: "Hecarim", archetype: "diver", lanes: ["Jungle"], roles: ["Fighter", "Tank"], damageType: "AD", difficulty: "Medium", tags: ["engage", "mobility"] },
  { name: "Heimerdinger", archetype: "artillery", lanes: ["Mid", "Baron"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["poke", "zone"] },
  { name: "Irelia", archetype: "skirmisher", lanes: ["Mid", "Baron"], roles: ["Fighter"], damageType: "AD", difficulty: "Hard", tags: ["mobility", "duelist"] },
  { name: "Janna", archetype: "enchanter", lanes: ["Support"], roles: ["Support", "Enchanter"], damageType: "AP", difficulty: "Easy", tags: ["peel", "sustain"] },
  { name: "Jarvan IV", archetype: "diver", lanes: ["Jungle", "Baron"], roles: ["Tank", "Fighter"], damageType: "AD", difficulty: "Easy", tags: ["engage", "frontline"] },
  { name: "Jax", archetype: "skirmisher", lanes: ["Baron", "Jungle"], roles: ["Fighter"], damageType: "Mixed", difficulty: "Medium", tags: ["scaling", "splitpush"] },
  { name: "Jayce", archetype: "artillery", lanes: ["Baron", "Mid"], roles: ["Fighter", "Marksman"], damageType: "AD", difficulty: "Hard", tags: ["poke", "burst"] },
  { name: "Jhin", archetype: "utilityMarksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Medium", tags: ["pick", "burst"] },
  { name: "Jinx", archetype: "hypercarry", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Easy", tags: ["scaling", "dps"] },
  { name: "Kai'Sa", archetype: "hypercarry", lanes: ["Dragon"], roles: ["Marksman"], damageType: "Mixed", difficulty: "Medium", tags: ["mobility", "burst"] },
  { name: "Kalista", archetype: "skirmishMarksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Hard", tags: ["mobility", "duelist"] },
  { name: "Karma", archetype: "enchanter", lanes: ["Support", "Mid"], roles: ["Support", "Mage"], damageType: "AP", difficulty: "Easy", tags: ["poke", "peel"] },
  { name: "Kassadin", archetype: "assassin", lanes: ["Mid"], roles: ["Assassin", "Mage"], damageType: "AP", difficulty: "Hard", tags: ["scaling", "mobility"] },
  { name: "Katarina", archetype: "assassin", lanes: ["Mid"], roles: ["Assassin"], damageType: "AP", difficulty: "Hard", tags: ["mobility", "reset"] },
  { name: "Kayle", archetype: "hypercarry", lanes: ["Baron"], roles: ["Fighter", "Marksman"], damageType: "Mixed", difficulty: "Medium", tags: ["scaling", "supportive"] },
  { name: "Kayn", archetype: "assassin", lanes: ["Jungle"], roles: ["Assassin", "Fighter"], damageType: "AD", difficulty: "Hard", tags: ["mobility", "sustain"] },
  { name: "Kennen", archetype: "burstMage", lanes: ["Baron", "Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["engage", "zone"] },
  { name: "Kha'Zix", archetype: "assassin", lanes: ["Jungle"], roles: ["Assassin"], damageType: "AD", difficulty: "Medium", tags: ["pick", "burst"] },
  { name: "Kindred", archetype: "skirmishMarksman", lanes: ["Jungle"], roles: ["Marksman"], damageType: "AD", difficulty: "Hard", tags: ["mobility", "scaling"] },
  { name: "Kog'Maw", archetype: "hypercarry", lanes: ["Dragon"], roles: ["Marksman"], damageType: "Mixed", difficulty: "Medium", tags: ["dps", "antiTank"] },
  { name: "Lee Sin", archetype: "diver", lanes: ["Jungle"], roles: ["Fighter"], damageType: "AD", difficulty: "Hard", tags: ["mobility", "pick"] },
  { name: "Leona", archetype: "warden", lanes: ["Support"], roles: ["Tank", "Support"], damageType: "AP", difficulty: "Easy", tags: ["engage", "cc"] },
  { name: "Lillia", archetype: "skirmisher", lanes: ["Jungle", "Baron"], roles: ["Fighter", "Mage"], damageType: "AP", difficulty: "Medium", tags: ["mobility", "antiTank"] },
  { name: "Lissandra", archetype: "burstMage", lanes: ["Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["pick", "cc"] },
  { name: "Lucian", archetype: "marksman", lanes: ["Dragon", "Mid"], roles: ["Marksman"], damageType: "AD", difficulty: "Medium", tags: ["burst", "mobility"] },
  { name: "Lulu", archetype: "enchanter", lanes: ["Support"], roles: ["Support", "Enchanter"], damageType: "AP", difficulty: "Easy", tags: ["peel", "scaling"] },
  { name: "Lux", archetype: "artillery", lanes: ["Mid", "Support"], roles: ["Mage"], damageType: "AP", difficulty: "Easy", tags: ["poke", "pick"] },
  { name: "Malphite", archetype: "warden", lanes: ["Baron", "Support"], roles: ["Tank"], damageType: "AP", difficulty: "Easy", tags: ["engage", "frontline"] },
  { name: "Maokai", archetype: "guardian", lanes: ["Baron", "Support"], roles: ["Tank"], damageType: "AP", difficulty: "Easy", tags: ["frontline", "cc", "zone"] },
  { name: "Master Yi", archetype: "skirmisher", lanes: ["Jungle"], roles: ["Fighter"], damageType: "AD", difficulty: "Easy", tags: ["dps", "reset"] },
  { name: "Mel", archetype: "burstMage", lanes: ["Mid", "Support"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["poke", "zone"] },
  { name: "Milio", archetype: "enchanter", lanes: ["Support"], roles: ["Support", "Enchanter"], damageType: "AP", difficulty: "Easy", tags: ["peel", "buff"] },
  { name: "Miss Fortune", archetype: "marksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Easy", tags: ["poke", "aoe"] },
  { name: "Mordekaiser", archetype: "juggernaut", lanes: ["Baron"], roles: ["Fighter"], damageType: "AP", difficulty: "Easy", tags: ["frontline", "antiTank"] },
  { name: "Morgana", archetype: "catcher", lanes: ["Mid", "Support"], roles: ["Mage", "Support"], damageType: "AP", difficulty: "Easy", tags: ["pick", "peel"] },
  { name: "Nami", archetype: "enchanter", lanes: ["Support"], roles: ["Support", "Enchanter"], damageType: "AP", difficulty: "Easy", tags: ["sustain", "engage"] },
  { name: "Nasus", archetype: "juggernaut", lanes: ["Baron"], roles: ["Fighter", "Tank"], damageType: "AD", difficulty: "Easy", tags: ["scaling", "frontline"] },
  { name: "Nautilus", archetype: "warden", lanes: ["Support", "Jungle"], roles: ["Tank", "Support"], damageType: "AP", difficulty: "Easy", tags: ["engage", "cc"] },
  { name: "Nidalee", archetype: "specialist", lanes: ["Jungle"], roles: ["Assassin", "Mage"], damageType: "Mixed", difficulty: "Hard", tags: ["poke", "mobility"] },
  { name: "Nilah", archetype: "skirmishMarksman", lanes: ["Dragon"], roles: ["Marksman", "Fighter"], damageType: "AD", difficulty: "Hard", tags: ["dps", "engage"] },
  { name: "Nocturne", archetype: "diver", lanes: ["Jungle"], roles: ["Assassin", "Fighter"], damageType: "AD", difficulty: "Medium", tags: ["pick", "engage"] },
  { name: "Norra", archetype: "enchanter", lanes: ["Support"], roles: ["Support", "Mage"], damageType: "AP", difficulty: "Medium", tags: ["poke", "zone"] },
  { name: "Nunu & Willump", archetype: "guardian", lanes: ["Jungle"], roles: ["Tank"], damageType: "AP", difficulty: "Easy", tags: ["engage", "sustain"] },
  { name: "Olaf", archetype: "juggernaut", lanes: ["Jungle", "Baron"], roles: ["Fighter"], damageType: "AD", difficulty: "Easy", tags: ["frontline", "sustain"] },
  { name: "Orianna", archetype: "burstMage", lanes: ["Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["zone", "scaling"] },
  { name: "Ornn", archetype: "guardian", lanes: ["Baron"], roles: ["Tank"], damageType: "AP", difficulty: "Easy", tags: ["frontline", "engage"] },
  { name: "Pantheon", archetype: "diver", lanes: ["Jungle", "Mid", "Support"], roles: ["Fighter", "Assassin"], damageType: "AD", difficulty: "Easy", tags: ["pick", "laneBully"] },
  { name: "Poppy", archetype: "guardian", lanes: ["Baron", "Jungle", "Support"], roles: ["Tank", "Fighter"], damageType: "AD", difficulty: "Medium", tags: ["antiDash", "peel"] },
  { name: "Pyke", archetype: "catcher", lanes: ["Support"], roles: ["Support", "Assassin"], damageType: "AD", difficulty: "Hard", tags: ["pick", "mobility"] },
  { name: "Rakan", archetype: "catcher", lanes: ["Support"], roles: ["Support", "Tank"], damageType: "AP", difficulty: "Medium", tags: ["engage", "peel"] },
  { name: "Rammus", archetype: "guardian", lanes: ["Jungle"], roles: ["Tank"], damageType: "AP", difficulty: "Easy", tags: ["frontline", "antiAD"] },
  { name: "Rell", archetype: "warden", lanes: ["Support"], roles: ["Tank", "Support"], damageType: "AP", difficulty: "Medium", tags: ["engage", "frontline"] },
  { name: "Renekton", archetype: "diver", lanes: ["Baron"], roles: ["Fighter"], damageType: "AD", difficulty: "Easy", tags: ["laneBully", "burst"] },
  { name: "Rengar", archetype: "assassin", lanes: ["Jungle", "Baron"], roles: ["Assassin", "Fighter"], damageType: "AD", difficulty: "Medium", tags: ["pick", "burst"] },
  { name: "Riven", archetype: "skirmisher", lanes: ["Baron"], roles: ["Fighter"], damageType: "AD", difficulty: "Hard", tags: ["mobility", "burst"] },
  { name: "Rumble", archetype: "battlemage", lanes: ["Baron", "Mid"], roles: ["Mage", "Fighter"], damageType: "AP", difficulty: "Medium", tags: ["zone", "antiTank"] },
  { name: "Ryze", archetype: "battlemage", lanes: ["Mid", "Baron"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["scaling", "dps"] },
  { name: "Samira", archetype: "skirmishMarksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Hard", tags: ["engage", "burst"] },
  { name: "Senna", archetype: "utilityMarksman", lanes: ["Support", "Dragon"], roles: ["Marksman", "Support"], damageType: "AD", difficulty: "Medium", tags: ["poke", "scaling"] },
  { name: "Seraphine", archetype: "enchanter", lanes: ["Support", "Mid"], roles: ["Support", "Mage"], damageType: "AP", difficulty: "Easy", tags: ["poke", "zone"] },
  { name: "Sett", archetype: "juggernaut", lanes: ["Baron", "Support"], roles: ["Fighter", "Tank"], damageType: "AD", difficulty: "Easy", tags: ["frontline", "engage"] },
  { name: "Shen", archetype: "guardian", lanes: ["Baron"], roles: ["Tank"], damageType: "AD", difficulty: "Medium", tags: ["peel", "global"] },
  { name: "Shyvana", archetype: "juggernaut", lanes: ["Jungle", "Baron"], roles: ["Fighter"], damageType: "Mixed", difficulty: "Easy", tags: ["frontline", "scaling"] },
  { name: "Singed", archetype: "specialist", lanes: ["Baron"], roles: ["Tank", "Specialist"], damageType: "AP", difficulty: "Medium", tags: ["frontline", "zone"] },
  { name: "Sion", archetype: "guardian", lanes: ["Baron"], roles: ["Tank"], damageType: "AD", difficulty: "Easy", tags: ["frontline", "engage"] },
  { name: "Sivir", archetype: "marksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Easy", tags: ["waveclear", "scaling"] },
  { name: "Smolder", archetype: "hypercarry", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Easy", tags: ["scaling", "poke"] },
  { name: "Sona", archetype: "enchanter", lanes: ["Support"], roles: ["Support", "Enchanter"], damageType: "AP", difficulty: "Easy", tags: ["sustain", "scaling"] },
  { name: "Soraka", archetype: "enchanter", lanes: ["Support"], roles: ["Support", "Enchanter"], damageType: "AP", difficulty: "Easy", tags: ["sustain", "peel"] },
  { name: "Swain", archetype: "battlemage", lanes: ["Mid", "Support"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["frontline", "sustain"] },
  { name: "Syndra", archetype: "burstMage", lanes: ["Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["burst", "pick"] },
  { name: "Talon", archetype: "assassin", lanes: ["Mid", "Jungle"], roles: ["Assassin"], damageType: "AD", difficulty: "Medium", tags: ["mobility", "burst"] },
  { name: "Teemo", archetype: "specialist", lanes: ["Baron", "Mid"], roles: ["Marksman", "Specialist"], damageType: "AP", difficulty: "Easy", tags: ["poke", "zone"] },
  { name: "Thresh", archetype: "catcher", lanes: ["Support"], roles: ["Support", "Tank"], damageType: "AP", difficulty: "Hard", tags: ["pick", "peel"] },
  { name: "Tristana", archetype: "hypercarry", lanes: ["Dragon", "Mid"], roles: ["Marksman"], damageType: "AD", difficulty: "Easy", tags: ["scaling", "mobility"] },
  { name: "Tryndamere", archetype: "skirmisher", lanes: ["Baron", "Jungle"], roles: ["Fighter"], damageType: "AD", difficulty: "Easy", tags: ["splitpush", "crit"] },
  { name: "Twisted Fate", archetype: "burstMage", lanes: ["Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["pick", "global"] },
  { name: "Twitch", archetype: "hypercarry", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Medium", tags: ["scaling", "burst"] },
  { name: "Urgot", archetype: "juggernaut", lanes: ["Baron"], roles: ["Fighter", "Tank"], damageType: "AD", difficulty: "Medium", tags: ["antiTank", "frontline"] },
  { name: "Varus", archetype: "pokeMarksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "Mixed", difficulty: "Medium", tags: ["poke", "antiTank"] },
  { name: "Vayne", archetype: "hypercarry", lanes: ["Dragon", "Baron"], roles: ["Marksman"], damageType: "AD", difficulty: "Hard", tags: ["antiTank", "mobility"] },
  { name: "Veigar", archetype: "burstMage", lanes: ["Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Easy", tags: ["scaling", "burst"] },
  { name: "Vel'Koz", archetype: "artillery", lanes: ["Mid", "Support"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["poke", "antiTank"] },
  { name: "Vex", archetype: "burstMage", lanes: ["Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Easy", tags: ["pick", "antiDash"] },
  { name: "Vi", archetype: "diver", lanes: ["Jungle"], roles: ["Fighter"], damageType: "AD", difficulty: "Easy", tags: ["engage", "pick"] },
  { name: "Viego", archetype: "skirmisher", lanes: ["Jungle"], roles: ["Fighter"], damageType: "AD", difficulty: "Medium", tags: ["dps", "reset"] },
  { name: "Viktor", archetype: "battlemage", lanes: ["Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["scaling", "zone"] },
  { name: "Vladimir", archetype: "battlemage", lanes: ["Mid", "Baron"], roles: ["Mage"], damageType: "AP", difficulty: "Medium", tags: ["sustain", "scaling"] },
  { name: "Volibear", archetype: "juggernaut", lanes: ["Jungle", "Baron"], roles: ["Fighter", "Tank"], damageType: "Mixed", difficulty: "Easy", tags: ["engage", "frontline"] },
  { name: "Warwick", archetype: "diver", lanes: ["Jungle"], roles: ["Fighter"], damageType: "AD", difficulty: "Easy", tags: ["sustain", "pick"] },
  { name: "Wukong", archetype: "diver", lanes: ["Jungle", "Baron"], roles: ["Fighter"], damageType: "AD", difficulty: "Easy", tags: ["engage", "frontline"] },
  { name: "Xayah", archetype: "marksman", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Medium", tags: ["peel", "scaling"] },
  { name: "Xin Zhao", archetype: "diver", lanes: ["Jungle"], roles: ["Fighter"], damageType: "AD", difficulty: "Easy", tags: ["engage", "duelist"] },
  { name: "Yasuo", archetype: "skirmisher", lanes: ["Mid", "Baron"], roles: ["Fighter", "Assassin"], damageType: "AD", difficulty: "Hard", tags: ["mobility", "crit"] },
  { name: "Yone", archetype: "skirmisher", lanes: ["Mid", "Baron"], roles: ["Fighter", "Assassin"], damageType: "Mixed", difficulty: "Hard", tags: ["engage", "burst"] },
  { name: "Yuumi", archetype: "enchanter", lanes: ["Support"], roles: ["Support", "Enchanter"], damageType: "AP", difficulty: "Easy", tags: ["peel", "sustain"] },
  { name: "Zed", archetype: "assassin", lanes: ["Mid"], roles: ["Assassin"], damageType: "AD", difficulty: "Hard", tags: ["burst", "mobility"] },
  { name: "Zeri", archetype: "hypercarry", lanes: ["Dragon"], roles: ["Marksman"], damageType: "AD", difficulty: "Hard", tags: ["mobility", "dps"] },
  { name: "Ziggs", archetype: "artillery", lanes: ["Mid", "Dragon"], roles: ["Mage"], damageType: "AP", difficulty: "Easy", tags: ["poke", "zone"] },
  { name: "Zilean", archetype: "enchanter", lanes: ["Support", "Mid"], roles: ["Support", "Mage"], damageType: "AP", difficulty: "Medium", tags: ["peel", "scaling"] },
  { name: "Zoe", archetype: "burstMage", lanes: ["Mid"], roles: ["Mage"], damageType: "AP", difficulty: "Hard", tags: ["poke", "pick"] },
  { name: "Zyra", archetype: "artillery", lanes: ["Support", "Mid"], roles: ["Mage", "Support"], damageType: "AP", difficulty: "Medium", tags: ["zone", "poke"] },
];


const archetypeProfiles = {
  juggernaut: { label: "釉뚮（? / ?嫄곕꽋", baseTags: ["frontline", "dps", "antiMelee"], coreItems: ["Black Cleaver", "Sundered Sky", "Sterak's Gage"], situationalItems: ["Death's Dance", "Maw of Malmortius", "Guardian Angel", "Amaranth's Twinguard"], boots: ["Mercury's Treads", "Plated Steelcaps", "Gluttonous Greaves"], enchants: ["Glorious", "Stasis", "Protobelt"], strengths: ["吏㏃? 援먯쟾蹂대떎 湲?援먯쟾?먯꽌 ?꾨젰??而ㅼ쭛?덈떎.", "?욌씪?몄쓣 ?몄슦硫??ъ씠???뺣컯源뚯? 寃명븷 ???덉뒿?덈떎."], weaknesses: ["?ш굅由??뺣컯怨?移댁씠??議고빀???붾뱾由????덉뒿?덈떎.", "?쒓컙 吏꾩엯蹂대떎??媛곸쓣 ?ㅻ옒 遊먯빞 ?⑸땲??"], laneTip: "?곷? ?듭떖 ?ㅽ궗??鍮좎죱????湲멸쾶 異붽꺽?섎뒗 援먯쟾???ㅺ퀎?섏꽭??", teamfightTip: "?쒗??먯꽌??泥?吏꾩엯蹂대떎 ?곷? 二쇱슂 援곗쨷 ?쒖뼱媛 鍮좎쭊 ???ъ쭊?낆씠 ???덉젙?곸엯?덈떎." },
  diver: { label: "?ㅼ씠踰?, baseTags: ["engage", "mobility", "burst"], coreItems: ["Trinity Force", "Sundered Sky", "Death's Dance"], situationalItems: ["Maw of Malmortius", "Sterak's Gage", "Guardian Angel", "Black Cleaver"], boots: ["Mercury's Treads", "Plated Steelcaps", "Ionian Boots of Lucidity"], enchants: ["Protobelt", "Stasis", "Glorious"], strengths: ["?먭굅由??듭떖 ?쒕윭瑜?吏곸젒 ?뺣컯?섍린 醫뗭뒿?덈떎.", "珥덉쨷諛?二쇰룄沅뚭낵 ?⑸쪟 ??대컢??媛뺥빀?덈떎."], weaknesses: ["泥?吏꾩엯 ?ㅽ뙣 ??蹂듦? ?숈꽑???뉗뒿?덈떎.", "怨쇳븳 ?좎쭊?낆? ?꾧뎔 ?⑸쪟 ??대컢怨??닿툔?????덉뒿?덈떎."], laneTip: "?쇱씤蹂대떎 ?⑸쪟 媛곸쓣 癒쇱? 怨꾩궛?섍퀬, ?뚭퇋紐?援먯쟾?먯꽌 ?レ옄 ?곗쐞瑜?留뚮뱶????吏묒쨷?섏꽭??", teamfightTip: "?곷? ?듭떖 ?쒕윭???앹〈 ?ㅽ궗???뺤씤????吏꾩엯?섎㈃ ?깃났 ?뺣쪧???ш쾶 ?щ씪媛묐땲??" },
  warden: { label: "?대땲???깆빱", baseTags: ["frontline", "engage", "cc"], coreItems: ["Sunfire Aegis", "Thornmail", "Amaranth's Twinguard"], situationalItems: ["Force of Nature", "Frozen Heart", "Randuin's Omen", "Warmog's Armor"], boots: ["Mercury's Treads", "Plated Steelcaps", "Ionian Boots of Lucidity"], enchants: ["Gargoyle", "Locket", "Glorious"], strengths: ["議고빀???뺤젙 ?대땲?쒕? 異붽??⑸땲??", "?쒖빞 ?꾪닾? ?ㅻ툕?앺듃 ??援먯쟾??媛뺥빀?덈떎."], weaknesses: ["?ㅼ뼱媛??????꾩냽??遺議깊븯硫?媛移섍? 以꾩뼱??땲??", "?ы궧留??꾩쟻?섎뒗 援щ룄?먯꽌??泥대젰 愿由ш? 以묒슂?⑸땲??"], laneTip: "??踰덉뿉 紐⑤뱺 ?ㅽ궗???곌린蹂대떎 ?듭떖 援곗쨷 ?쒖뼱瑜??꾧뺨 ?뺤젙 援먯쟾??留뚮뱶?몄슂.", teamfightTip: "?좎쭊?낃낵 ?꾩냽 吏꾩엯 以??대뼡 ??븷???꾩슂?쒖? 癒쇱? ?뺥븯怨??쒗?瑜??ъ꽭??" },
  guardian: { label: "媛?붿뼵 ?깆빱", baseTags: ["frontline", "peel", "cc"], coreItems: ["Sunfire Aegis", "Force of Nature", "Amaranth's Twinguard"], situationalItems: ["Frozen Heart", "Thornmail", "Randuin's Omen", "Warmog's Armor"], boots: ["Mercury's Treads", "Plated Steelcaps", "Ionian Boots of Lucidity"], enchants: ["Locket", "Gargoyle", "Redemption"], strengths: ["?꾧뎔 罹먮━瑜?吏?ㅻŉ 援먯쟾 ?쒓컙???섎┫ ???덉뒿?덈떎.", "?뚯쭊 議고빀 ?곷?濡??덉젙?곸씤 諛쏅뒗 媛곸쓣 留뚮벊?덈떎."], weaknesses: ["?쇱옄 寃뚯엫???곕쑉由щ뒗 ??컻?μ? ??뒿?덈떎.", "諛깅씪?몄씠 ?놁쑝硫?媛移섍? 以꾩뼱??땲??"], laneTip: "?곷???癒쇱? ?ㅼ뼱?ㅻ뒗 ?吏곸엫??諛쏆븘移섎뒗 ?앹쑝濡?援먯쟾???ㅺ퀎?섏꽭??", teamfightTip: "吏꾩엯蹂대떎???꾧뎔 ?듭떖 ?쒕윭媛 ?쒗븷 怨듦컙??留뚮뱶????吏묒쨷?섏꽭??" },
  assassin: { label: "?붿궡??, baseTags: ["burst", "mobility", "pick"], coreItems: ["Youmuu's Ghostblade", "Duskblade of Draktharr", "Edge of Night"], situationalItems: ["Serpent's Fang", "Serylda's Grudge", "Guardian Angel", "Maw of Malmortius"], boots: ["Boots of Dynamism", "Ionian Boots of Lucidity", "Mercury's Treads"], enchants: ["Stasis", "Protobelt", "Quicksilver"], strengths: ["?ъ씠???쒖빞瑜?癒뱀? ???⑤룆 ?ъ쓣 留뚮뱾湲?醫뗭뒿?덈떎.", "?곷? 臾쇰じ 議고빀??鍮좊Ⅴ寃?遺뺢눼?쒗궗 ???덉뒿?덈떎."], weaknesses: ["?깆빱媛 留롪굅??蹂댄샇 ?섎떒??留롮쑝硫?吏꾩엯 媛移섍? ?⑥뼱吏묐땲??", "泥?肄ㅻ낫 ?ㅽ뙣 ???ъ쭊?낆씠 源뚮떎濡?뒿?덈떎."], laneTip: "??踰덉뿉 ?ъ쓣 ?닿린蹂대떎 泥대젰怨??먮㈇??癒쇱? 鍮쇰뒗 媛곷룄 媛移섍? ?쎈땲??", teamfightTip: "痢〓㈃ 媛곸쓣 癒쇱? ?↔퀬, ?곷? 蹂댄샇 ?ㅽ궗??鍮좎죱????吏꾩엯?섏꽭??" },
  burstMage: { label: "踰꾩뒪??硫붿씠吏", baseTags: ["burst", "pick", "magic"], coreItems: ["Luden's Echo", "Infinity Orb", "Rabadon's Deathcap"], situationalItems: ["Crown of the Shattered Queen", "Horizon Focus", "Morellonomicon", "Cosmic Drive"], boots: ["Boots of Mana", "Ionian Boots of Lucidity", "Mercury's Treads"], enchants: ["Stasis", "Protobelt", "Veil"], strengths: ["吏㏃? 李쎄뎄?먯꽌 ?뺤젙?곸씤 ?쇳빐瑜?諛???ｊ린 醫뗭뒿?덈떎.", "?쎄낵 ?쒖빞 ?μ븙 ?④퀎?먯꽌 ?뺣컯?μ씠 ?쎈땲??"], weaknesses: ["湲??꾪닾?먯꽌 ?붾젰???딄만 ???덉뒿?덈떎.", "?뚯쭊 議고빀??癒쇱? 臾쇰━硫??ъ??섏씠 臾대꼫吏묐땲??"], laneTip: "?ㅽ궗 ?곸쨷 媛곸쓣 留뚮뱾 ???덈뒗 誘몃땲???⑥씠釉뚯? ?쒖빞瑜?癒쇱? ?뺣낫?섏꽭??", teamfightTip: "?곷????뚯쭊 寃쎈줈蹂대떎???곕━ ????곕씪?????덈뒗 媛곸뿉??癒쇱? 留욎텛??寃껋씠 以묒슂?⑸땲??" },
  battlemage: { label: "諛고? 硫붿씠吏", baseTags: ["magic", "dps", "zone"], coreItems: ["Liandry's Torment", "Rylai's Crystal Scepter", "Rabadon's Deathcap"], situationalItems: ["Riftmaker", "Cosmic Drive", "Morellonomicon", "Crown of the Shattered Queen"], boots: ["Boots of Mana", "Ionian Boots of Lucidity", "Mercury's Treads"], enchants: ["Stasis", "Protobelt", "Veil"], strengths: ["援먯쟾 ?쒓컙??湲몄닔濡?吏???붾젰???댁븘?⑸땲??", "?깆빱 ?곷?濡쒕룄 ?덉젙?곸씤 湲곗뿬媛 媛?ν빀?덈떎."], weaknesses: ["?ъ??섏씠 遺??⑤㈃ ?붾젰???섏삤湲??꾩뿉 ?섎┫ ???덉뒿?덈떎.", "珥덈컲 ?쇱씤 二쇰룄沅뚯? ?곸꽦 ?곹뼢??留롮씠 諛쏆뒿?덈떎."], laneTip: "吏㏃? ?ㅽ궗 援먰솚蹂대떎 ?⑥씠釉?二쇰룄沅뚭낵 吏꾩엯 媛?李⑤떒??吏묒쨷?섏꽭??", teamfightTip: "?곸씠 吏?섍????섎뒗 醫곸? 怨듦컙??癒쇱? ?먯쑀?섎㈃ ?뺣컯???ш쾶 ?щ씪媛묐땲??" },
  artillery: { label: "?ы궧 硫붿씠吏", baseTags: ["poke", "zone", "magic"], coreItems: ["Luden's Echo", "Horizon Focus", "Rabadon's Deathcap"], situationalItems: ["Liandry's Torment", "Morellonomicon", "Infinity Orb", "Crown of the Shattered Queen"], boots: ["Boots of Mana", "Ionian Boots of Lucidity", "Mercury's Treads"], enchants: ["Stasis", "Veil", "Protobelt"], strengths: ["?ㅻ툕?앺듃 ?꾩뿉 ?곷? 泥대젰??癒쇱? 源롮븘 援먯쟾 ?곗쐞瑜?留뚮벊?덈떎.", "吏꾩엯 議고빀???묎렐?섍린 ?꾩뿉 ?섏쓣 鍮쇨린 醫뗭뒿?덈떎."], weaknesses: ["吏곸젒 諛쏆븘移섎뒗 ?꾨㈃?꾩? ?쏀빀?덈떎.", "痢〓㈃ 吏꾩엯??痍⑥빟???쒖빞 愿由ш? ?꾩닔?낅땲??"], laneTip: "?쇱씤 ?몄떆蹂대떎???곷?媛 ?ㅽ궗???쇳븯湲??대젮??媛곸쓣 留뚮뱶????吏묒쨷?섏꽭??", teamfightTip: "?꾪닾媛 ?대━湲???泥대젰 ?곗쐞瑜?留뚮뱶??寃껋씠 媛?????꾨Т?낅땲??" },
  marksman: { label: "?먮뵜", baseTags: ["dps", "scaling", "physical"], coreItems: ["Infinity Edge", "Magnetic Blaster", "Bloodthirster"], situationalItems: ["Mortal Reminder", "Guardian Angel", "Runaan's Hurricane", "Navori Quickblades"], boots: ["Berserker's Greaves", "Gluttonous Greaves", "Mercury's Treads"], enchants: ["Stasis", "Quicksilver", "Glorious"], strengths: ["?꾨컲 ?쒗???吏???붾젰??梨낆엫吏묐땲??", "?욌씪?몄씠 諛쏆퀜以꾩닔濡??붾젰 ?⑥쑉??而ㅼ쭛?덈떎."], weaknesses: ["吏꾩엯 議고빀怨??붿궡?먯뿉寃??ъ????뺣컯???ш쾶 諛쏆뒿?덈떎.", "珥덈컲 ?쇱씤???ㅼ닔???섎꼸?곌? ?쎈땲??"], laneTip: "誘몃땲??留됲?蹂대떎??泥대젰怨??ㅽ렆??吏?ㅻ뒗 ?덉젙?곸씤 ?쇱씤?꾩씠 以묒슂?⑸땲??", teamfightTip: "媛??媛源뚯슫 ?꾪삊遺??李⑤텇??移섎㈃???앹〈 ?ㅽ궗??癒쇱? ?꾨겮?몄슂." },
  utilityMarksman: { label: "?좏떥 ?먮뵜", baseTags: ["dps", "poke", "cc"], coreItems: ["Infinity Edge", "Runaan's Hurricane", "Mortal Reminder"], situationalItems: ["Magnetic Blaster", "Bloodthirster", "Guardian Angel", "Navori Quickblades"], boots: ["Berserker's Greaves", "Gluttonous Greaves", "Mercury's Treads"], enchants: ["Quicksilver", "Stasis", "Glorious"], strengths: ["?쒖닔 ???몄뿉???좏떥由ы떚? 援먯쟾 媛쒖떆瑜??뷀븷 ???덉뒿?덈떎.", "?쇱씤?꾧낵 以묐컲 援먯쟾?먯꽌 湲고쉶 李쎌텧 ?λ젰??醫뗭뒿?덈떎."], weaknesses: ["?쒖닔 ?섏씠?쇱틦由щ낫????湲곕?媛믪씠 ??쓣 ???덉뒿?덈떎.", "?ㅽ궗 ?곸쨷???곕씪 泥닿컧 ?깅뒫 李⑥씠媛 ?쎈땲??"], laneTip: "?쇱씤 ?곗쐞蹂대떎 ?ㅽ궗 ?곸쨷怨??⑥씠釉?而⑦듃濡ㅻ줈 癒쇱? 怨듦컙???≪쑝?몄슂.", teamfightTip: "吏곸젒 媛곸쓣 ?닿린蹂대떎, ?꾧뎔怨??숈떆???ㅽ궗??寃뱀퀜 留욎텛??履쎌씠 ???덉젙?곸엯?덈떎." },
  pokeMarksman: { label: "?ы궧 ?먮뵜", baseTags: ["poke", "dps", "physical"], coreItems: ["Manamune", "Serylda's Grudge", "Infinity Edge"], situationalItems: ["Mortal Reminder", "Runaan's Hurricane", "Guardian Angel", "Bloodthirster"], boots: ["Ionian Boots of Lucidity", "Berserker's Greaves", "Mercury's Treads"], enchants: ["Stasis", "Quicksilver", "Glorious"], strengths: ["?꾪닾媛 ?대━湲??꾩뿉 泥대젰??鍮쇰뒗 ???뱁솕?⑸땲??", "吏꾩엯 ???뺣컯怨??ъ??붾떇 媛뺤젣?μ씠 醫뗭뒿?덈떎."], weaknesses: ["?뺣㈃ ?κ린???붾젰? ?섏씠?쇱틦由щ낫????쓣 ???덉뒿?덈떎.", "?곸쨷瑜좎뿉 ?곕씪 湲곕?媛믪씠 ?ш쾶 ?щ씪吏묐땲??"], laneTip: "媛뺥븳 ??대컢???ㅺ린 ?꾧퉴吏??臾대━???꾨㈃?꾨낫??泥대젰 援먰솚 ?꾩쟻??吏묒쨷?섏꽭??", teamfightTip: "?ㅻ툕?앺듃 ??援щ룄?먯꽌 癒쇱? 泥대젰??源롮븘 援먯쟾 議곌굔??諛붽씀??寃껋씠 ?듭떖?낅땲??" },
  hypercarry: { label: "?섏씠?쇱틦由?, baseTags: ["dps", "scaling", "antiTank"], coreItems: ["Infinity Edge", "Runaan's Hurricane", "Bloodthirster"], situationalItems: ["Mortal Reminder", "Guardian Angel", "Phantom Dancer", "Terminus"], boots: ["Berserker's Greaves", "Gluttonous Greaves", "Mercury's Treads"], enchants: ["Quicksilver", "Stasis", "Glorious"], strengths: ["寃뚯엫??湲몄뼱吏덉닔濡??밸━ 議곌굔???좊챸?댁쭛?덈떎.", "?욌씪?몄씠 ?덉쑝硫???컻?곸씤 ??뚯씠???붾젰???낅땲??"], weaknesses: ["珥덉쨷諛??뺣컯怨??쒖빞媛 遺議깊븯硫??깆옣 援ш컙???붾뱾由쎈땲??", "蹂댄샇媛 ?놁쑝硫?吏꾩엯 議고빀 ??묒씠 ?대졄?듬땲??"], laneTip: "?쇱씤???먰빐瑜?以꾩씠硫?泥???肄붿뼱 ??대컢源뚯? ?덉쟾?섍쾶 ?곌껐?섎뒗 ??吏묒쨷?섏꽭??", teamfightTip: "?앹〈湲곌? ?덈떎硫?理쒕?????쾶 ?곌퀬, ???듭떖 ?꾪삊??鍮좎쭏 ?뚭퉴吏 ??媛곸쓣 醫곹? ?≪쑝?몄슂." },
  skirmisher: { label: "?ㅼ빱誘몄뀛", baseTags: ["dps", "mobility", "duelist"], coreItems: ["Blade of the Ruined King", "Trinity Force", "Death's Dance"], situationalItems: ["Wit's End", "Guardian Angel", "Sterak's Gage", "Maw of Malmortius"], boots: ["Gluttonous Greaves", "Mercury's Treads", "Plated Steelcaps"], enchants: ["Stasis", "Protobelt", "Glorious"], strengths: ["1?1怨??뚭퇋紐?援먯쟾?먯꽌 ?꾨젰???믪뒿?덈떎.", "痢〓㈃ ?뺣컯怨?吏꾩엯 ???뺣━媛 ?곗뼱?⑸땲??"], weaknesses: ["?뺣㈃ 5?5?먯꽌 吏꾩엯 ??대컢??源뚮떎濡?뒿?덈떎.", "媛뺥븳 援곗쨷 ?쒖뼱 ?곌퀎??痍⑥빟?⑸땲??"], laneTip: "臾대━???ъ씤蹂대떎 吏㏃? 援먰솚 ?꾩쟻怨???대컢 ?몄???吏묒쨷?섏꽭??", teamfightTip: "吏곸젒 ?뺣㈃???щ뒗 ?????媛곸씠????踰덉㎏ ?뚮룞 吏꾩엯?쇰줈 媛移섍? 洹밸??붾맗?덈떎." },
  skirmishMarksman: { label: "洹쇱젒???먮뵜", baseTags: ["dps", "mobility", "burst"], coreItems: ["Infinity Edge", "Bloodthirster", "Phantom Dancer"], situationalItems: ["Mortal Reminder", "Guardian Angel", "Navori Quickblades", "The Collector"], boots: ["Berserker's Greaves", "Gluttonous Greaves", "Mercury's Treads"], enchants: ["Stasis", "Quicksilver", "Protobelt"], strengths: ["吏꾩엯 ????뵜怨??곗냽 援먯쟾??媛뺥빀?덈떎.", "?뺤떎??援먯쟾 媛곸뿉??湲곕?媛믪씠 ?쎈땲??"], weaknesses: ["?꾪닾 媛곸씠 ?닿툔?섎㈃ ?ш굅由ш? 吏㏃븘 ?먰빐媛 ?쎈땲??", "援곗쨷 ?쒖뼱??留ㅼ슦 誘쇨컧?⑸땲??"], laneTip: "?쒗룷?곗? ??대컢??留욎텣 吏㏃? ??뵜 援먰솚??諛섎났??二쇰룄沅뚯쓣 ?≪쑝?몄슂.", teamfightTip: "?곷? 二쇱슂 CC媛 鍮좎쭊 ???ㅼ뼱媛??罹먮━?μ씠 ?쒕?濡??섏샃?덈떎." },
  enchanter: { label: "?몄콌??, baseTags: ["peel", "sustain", "buff"], coreItems: ["Ardent Censer", "Staff of Flowing Water", "Harmonic Echo"], situationalItems: ["Imperial Mandate", "Redemption", "Dream Maker", "Protector's Vow"], boots: ["Ionian Boots of Lucidity", "Mercury's Treads", "Boots of Mana"], enchants: ["Redemption", "Locket", "Veil"], strengths: ["?꾧뎔 罹먮━????湲곕?媛믪쓣 ?ш쾶 ?뚯뼱?щ┰?덈떎.", "?ы궧怨??κ린?꾩뿉??泥대젰 ?곗쐞瑜??좎??섍린 醫뗭뒿?덈떎."], weaknesses: ["吏곸젒 ?욎쓣 ?닿린??紐몄씠 ?쏀빀?덈떎.", "?쒖빞媛 諛由щ㈃ ?ъ????뺣컯???ы빀?덈떎."], laneTip: "?쇱씤?꾩? 臾대━??援먰솚蹂대떎 ?ㅽ궗 援먰솚 ?꾩쟻怨?泥대젰 ?좎???吏묒쨷?섏꽭??", teamfightTip: "?꾧뎔 ?듭떖 ?쒕윭媛 ?쒗븷 ?쒓컙??1珥???踰뚯뼱以?ㅻ뒗 媛먭컖?쇰줈 ?ㅽ궗??諛곕텇?섏꽭??" },
  catcher: { label: "罹먯쿂", baseTags: ["pick", "cc", "roam"], coreItems: ["Imperial Mandate", "Protector's Vow", "Zeke's Convergence"], situationalItems: ["Knight's Vow", "Dawnshroud", "Locket", "Redemption"], boots: ["Ionian Boots of Lucidity", "Mercury's Treads", "Plated Steelcaps"], enchants: ["Glorious", "Locket", "Redemption"], strengths: ["?쒖빞 癒쇱? 癒뱀? 吏??뿉???ш컖??留뚮뱾湲?醫뗭뒿?덈떎.", "濡쒕컢怨????뚮젅?대줈 ?먮쫫???꾪솚?????덉뒿?덈떎."], weaknesses: ["?뺣㈃ ?섏떥?留?諛섎났?섎㈃ 媛移섍? 以꾩뼱??땲??", "?ㅽ궗 ?뺥솗?꾩? ?쒖빞 ?μ븙??以묒슂?⑸땲??"], laneTip: "?쇱씤??臾띠뿬 ?덇린蹂대떎 癒쇱? ?吏곸뿬 ?섏쟻 ?곗쐞瑜?留뚮뱶??洹몃┝???먯＜ 蹂댁꽭??", teamfightTip: "?쒗? ?꾩껜瑜??닿린蹂대떎 ?듭떖 ?섎굹瑜??뚯뼱?대뒗 ?앹쑝濡??꾪닾瑜??쒖옉?섏꽭??" },
  specialist: { label: "?ㅽ럹?쒕━?ㅽ듃", baseTags: ["poke", "zone", "scaling"], coreItems: ["Liandry's Torment", "Rylai's Crystal Scepter", "Cosmic Drive"], situationalItems: ["Morellonomicon", "Crown of the Shattered Queen", "Rabadon's Deathcap", "Horizon Focus"], boots: ["Boots of Mana", "Ionian Boots of Lucidity", "Mercury's Treads"], enchants: ["Stasis", "Glorious", "Veil"], strengths: ["?쇰컲?곸씤 ?쒗? ?몄쓽 ?낇듅???꾩옣 ?댁쁺??媛뺤젣?⑸땲??", "?곷?媛 ?듭닕?섏? ?딆쑝硫?泥닿컧 ?뺣컯???쎈땲??"], weaknesses: ["議고빀 ?댄빐?꾧? 遺議깊븯硫??쒖슜 ??씠 醫곸븘吏????덉뒿?덈떎.", "?뺤꽍?곸씤 ?욌씪??蹂댄샇媛 遺議깊븷 ???덉뒿?덈떎."], laneTip: "?곷?媛 ?レ뼱?섎뒗 吏?뺢낵 ?숈꽑??癒쇱? 留뚮뱾??寃뚯엫 ?띾룄瑜?鍮꾪듃????吏묒쨷?섏꽭??", teamfightTip: "?뺣㈃ ?밸?蹂대떎 吏???μ븙怨?寃쎈줈 李⑤떒?쇰줈 ?곷? ?먮떒??瑗ъ씠寃?留뚮뱶??寃껋씠 媛뺤젏?낅땲??" },
  marksmanAssassin: { label: "?섏씠釉뚮━???먮뵜", baseTags: ["burst", "mobility", "physical"], coreItems: ["Youmuu's Ghostblade", "The Collector", "Infinity Edge"], situationalItems: ["Mortal Reminder", "Guardian Angel", "Magnetic Blaster", "Serpent's Fang"], boots: ["Boots of Dynamism", "Berserker's Greaves", "Mercury's Treads"], enchants: ["Stasis", "Quicksilver", "Protobelt"], strengths: ["?쇱씤 ?곗쐞? ?ъ씠???뺣컯???숈떆???몃┫ ???덉뒿?덈떎.", "臾쇰じ 議고빀 ?곷?濡?鍮좊Ⅴ寃??쒗룷瑜??뚯뼱?щ┰?덈떎."], weaknesses: ["?뺥넻 ?먮뵜蹂대떎 ?뺣㈃ 吏???붾젰??遺議깊븷 ???덉뒿?덈떎.", "?쒖빞媛 ?놁쑝硫?吏꾩엯 ?먮떒???대젮?뚯쭛?덈떎."], laneTip: "?쇱씤???곗쐞瑜??뺣낫????癒쇱? ?吏곸뿬 留??꾩뿭???뺣컯??留뚮뱾??蹂댁꽭??", teamfightTip: "?꾩쟾???꾩뿴 ?ъ??섎낫???녾컖?먯꽌 吏㏐쾶 吏꾩엯?섎뒗 援щ룄媛 醫뗭뒿?덈떎." },
  marksmanFighter: { label: "釉뚮（????먮뵜", baseTags: ["burst", "durable", "physical"], coreItems: ["Youmuu's Ghostblade", "Black Cleaver", "Bloodthirster"], situationalItems: ["Guardian Angel", "Maw of Malmortius", "Serylda's Grudge", "Death's Dance"], boots: ["Gluttonous Greaves", "Mercury's Treads", "Plated Steelcaps"], enchants: ["Stasis", "Glorious", "Protobelt"], strengths: ["洹쇱쨷嫄곕━ 援먯쟾?먯꽌 踰꾪떚硫???뵜???닿린 醫뗭뒿?덈떎.", "?뺢? 援먯쟾怨??ㅻ끂?곕낵 援ш컙??媛뺥빀?덈떎."], weaknesses: ["?ш굅由?湲?議고빀 ?곷?濡쒕뒗 吏꾩엯 媛곸씠 以묒슂?⑸땲??", "?꾨컲 ?쒖닔 罹먮━?μ? ?꾪넻 ?먮뵜蹂대떎 ??쓣 ???덉뒿?덈떎."], laneTip: "媛곸씠 蹂댁씠吏 ?딆쑝硫?臾대━?섍쾶 ?섏? 留먭퀬, 醫곸? 怨듦컙 援먯쟾???좊룄?섏꽭??", teamfightTip: "?곷? ?듭떖 ?쒕윭? 嫄곕━瑜?醫곹엳湲??꾩뿉??怨쇳븯寃??욎쑝濡??섍?吏 ?딅뒗 寃껋씠 以묒슂?⑸땲??" },
};


const itemData = {
  "Ardent Censer": { category: "Support", summary: "怨듦꺽 ?띾룄 湲곕컲 罹먮━瑜?媛뺥솕?섎뒗 ????몄콌???꾩씠?쒖엯?덈떎." },
  "Black Cleaver": { category: "Fighter", summary: "諛⑹뼱?μ씠 ?볦씤 ?꾩뿴 ?곷?濡?釉뚮（?????湲곕?媛믪쓣 ?믪엯?덈떎." },
  "Blade of the Ruined King": { category: "Fighter", summary: "泥대젰 ?믪? ?꾩뿴怨?1?1 援щ룄??媛뺥븳 ????꾩씠?쒖엯?덈떎." },
  "Bloodthirster": { category: "Marksman", summary: "?쒓낵 ?≫삁???④퍡 梨숆꺼 ?쒗? ?덉젙?깆쓣 蹂댁셿?⑸땲??" },
  "Boots of Dynamism": { category: "Boots", summary: "?붿궡?먯? 濡쒕㉧媛 ?쒗룷瑜??щ━湲?醫뗭? 湲곕룞???좊컻?낅땲??" },
  "Boots of Mana": { category: "Boots", summary: "珥덉쨷諛?二쇰Ц ?쒓낵 留덈굹 ?댁쁺???뺣뒗 AP ?좊컻?낅땲??" },
  "Berserker's Greaves": { category: "Boots", summary: "?됲? 湲곕컲 ?쒕윭?먭쾶 媛??吏곴??곸씤 怨듦꺽 ?띾룄 ?좊컻?낅땲??" },
  "Chempunk Chainsword": { category: "Fighter", summary: "AD 湲곕컲 釉뚮（?媛 移섏쑀 媛먯냼瑜?梨숆만 ???⑥쑉?곸엯?덈떎." },
  "Cosmic Drive": { category: "Mage", summary: "吏㏃? 荑⑦??꾧낵 湲곕룞?깆씠 以묒슂??AP 梨뷀뵾?몄뿉 ??留욎뒿?덈떎." },
  "Crown of the Shattered Queen": { category: "Mage", summary: "?뚯쭊怨??붿궡 ?뺣컯??媛뺥븳 議고빀 ?곷?濡??앹〈?μ쓣 蹂댁셿?⑸땲??" },
  "Dawnshroud": { category: "Tank", summary: "?대땲?쒗삎 ?쒗룷?곌? 援먯쟾 媛쒖떆 ???꾩냽 ?붾젰??遺숈씠湲?醫뗭뒿?덈떎." },
  "Death's Dance": { category: "Fighter", summary: "AD 釉뚮（?媛 ?쒓컙 ??뵜??踰꾪떚硫??몄슦湲?醫뗭뒿?덈떎." },
  "Dream Maker": { category: "Support", summary: "?몄콌?곌? 援먯쟾怨?蹂댄샇 ?묒そ??遺?쒕읇寃?蹂댁“?댁쨳?덈떎." },
  "Duskblade of Draktharr": { category: "Assassin", summary: "?뺤떎??留덈Т由ъ? ?쒓컙 ??뵜???꾩슂??AD ?붿궡?먯슜 肄붿뼱?낅땲??" },
  "Edge of Night": { category: "Assassin", summary: "吏꾩엯 ?꾩뿉 ?듭떖 ?쒖뼱湲곕? ??踰?留됱븘二쇱뼱 ?붿궡 ?깃났瑜좎쓣 ?믪엯?덈떎." },
  "Force of Nature": { category: "Tank", summary: "AP ?쇳빐媛 留롮? 議고빀 ?곷?濡???쒖쟻??留덈쾿 ????좏깮吏?낅땲??" },
  "Frozen Heart": { category: "Tank", summary: "怨듦꺽 ?띾룄 湲곕컲 議고빀怨?AD 鍮꾩쨷???믪? ???곷?濡?媛뺥빀?덈떎." },
  "Gargoyle": { category: "Enchant", summary: "?깆빱媛 ?쒗? 以묒떖?먯꽌 ?ㅻ옒 踰꾪떚怨??띠쓣 ??醫뗭? ?몄콌?몄엯?덈떎." },
  "Glorious": { category: "Enchant", summary: "援먯쟾 媛쒖떆? 異붾끂 媛곸쓣 ?ш쾶 ?볧?二쇰뒗 ?몄콌?몄엯?덈떎." },
  "Gluttonous Greaves": { category: "Boots", summary: "吏??援먯쟾????? 梨뷀뵾?몄뿉寃??≫삁 湲곕컲 ?덉젙?깆쓣 ?뷀빀?덈떎." },
  "Guardian Angel": { category: "Defense", summary: "?꾨컲 援먯쟾?먯꽌 ??踰덉쓽 ?ㅼ닔瑜?蹂듦뎄?????덈뒗 ?덉쟾?μ튂?낅땲??" },
  "Harmonic Echo": { category: "Support", summary: "?쇱씤 ?좎??κ낵 ?뚭퇋紐?援먯쟾 ?뚮났???숈떆??吏?먰빀?덈떎." },
  "Horizon Focus": { category: "Mage", summary: "以묒옣嫄곕━ ?ы궧怨????ㅽ궗??蹂댁긽媛믪쓣 ?믪뿬以띾땲??" },
  "Imperial Mandate": { category: "Support", summary: "CC ?곌퀎媛 ?뺤떎???쒗룷?곌? ? ?붾젰??利앺룺?쒗궎湲?醫뗭뒿?덈떎." },
  "Infinity Edge": { category: "Marksman", summary: "移섎챸? 鍮뚮뱶??湲곕낯???섎뒗 ??뵜 肄붿뼱 ?꾩씠?쒖엯?덈떎." },
  "Infinity Orb": { category: "Mage", summary: "留덈Т由???뵜??以묒슂??AP 梨뷀뵾?몄쓽 ???뺣쪧???뚯뼱?щ┰?덈떎." },
  "Ionian Boots of Lucidity": { category: "Boots", summary: "?ㅽ궗 ?뚯쟾?⑥씠 以묒슂???쒗룷?곗? 罹먯뒪?곗뿉寃??⑥쑉?곸엯?덈떎." },
  "Knight's Vow": { category: "Support", summary: "?뱀젙 罹먮━瑜?蹂댄샇?댁빞 ?????쒗룷?곌? 媛??吏곴??곸쑝濡??좏깮?????덉뒿?덈떎." },
  "Liandry's Torment": { category: "Mage", summary: "?깆빱? 泥대젰 留롮? 議고빀 ?곷?濡?吏???쇳빐瑜?媛뺥솕?⑸땲??" },
  "Locket": { category: "Enchant", summary: "愿묒뿭 ??뵜怨??ㅼ씠釉뚮? ??踰?踰꾪뀲??????醫뗭? ? 蹂댄샇 ?몄콌?몄엯?덈떎." },
  "Luden's Echo": { category: "Mage", summary: "?쇱씤?꾧낵 泥?援먯쟾?먯꽌 ??컻?곸씤 二쇰Ц ?쇳빐瑜??쒓났?⑸땲??" },
  "Magnetic Blaster": { category: "Marksman", summary: "?ш굅由щ? ?쒖슜???좏?? ?ъ????뺣컯???꾩?以띾땲??" },
  "Maw of Malmortius": { category: "Defense", summary: "AD ?쒕윭媛 AP 踰꾩뒪?몃? 踰꾪뀲???????덉젙?곸엯?덈떎." },
  "Mercury's Treads": { category: "Boots", summary: "援곗쨷 ?쒖뼱? AP ?뺣컯???숈떆??以꾩씪 ???덈뒗 湲곕낯 ?좏깮吏?낅땲??" },
  "Morellonomicon": { category: "Mage", summary: "AP 梨뷀뵾?몄씠 移섏쑀 媛먯냼瑜?梨숆만 ??媛???덉젙?곸엯?덈떎." },
  "Mortal Reminder": { category: "Marksman", summary: "移섏쑀 媛먯냼? 諛⑹뼱 愿?듭쓣 ?④퍡 梨숆꺼 ?꾩뿴 ?뺣컯源뚯? 蹂댁셿?⑸땲??" },
  "Navori Quickblades": { category: "Marksman", summary: "?ㅽ궗 ?ъ궗?⑹씠 以묒슂??移섎챸? ?먮뵜???꾨컲 罹먮━?μ쓣 ?믪엯?덈떎." },
  "Phantom Dancer": { category: "Marksman", summary: "移댁씠?낃낵 吏???꾪닾 ?덉젙?깆씠 ?꾩슂???먮뵜?먭쾶 ?곹빀?⑸땲??" },
  "Plated Steelcaps": { category: "Boots", summary: "?됲? 湲곕컲 AD 議고빀 ?곷?濡?媛??吏곴??곸씤 諛⑹뼱 ?좊컻?낅땲??" },
  "Protector's Vow": { category: "Support", summary: "?꾧뎔 ?쒕윭瑜?蹂댄샇?댁빞 ?섎뒗 ?깆빱 ?쒗룷?곗쓽 湲곕낯 ?좏깮吏?낅땲??" },
  "Protobelt": { category: "Enchant", summary: "吏㏃? 吏꾩엯 嫄곕━??媛곷룄 議곗젅???꾩슂??梨뷀뵾?몄뿉寃???留욎뒿?덈떎." },
  "Quicksilver": { category: "Enchant", summary: "?섎뱶 CC??嫄몃━硫?寃뚯엫???앸굹??梨뷀뵾?몄뿉寃?媛??以묒슂?⑸땲??" },
  "Rabadon's Deathcap": { category: "Mage", summary: "AP 梨뷀뵾?몄쓽 ?쒖닔 ?붾젰 怨좎젏??梨낆엫吏?????肄붿뼱?낅땲??" },
  "Randuin's Omen": { category: "Tank", summary: "移섎챸?? ?됲? 鍮꾩쨷???믪? ?곸쓣 ?곷?????媛뺥빀?덈떎." },
  "Redemption": { category: "Enchant", summary: "硫由ъ꽌??援먯쟾 湲곗뿬? ?뚮났???뷀븷 ???덈뒗 ?좏떥 ?몄콌?몄엯?덈떎." },
  "Riftmaker": { category: "Mage", summary: "吏㏃? ??뵜蹂대떎 吏???붾젰??以묒슂??AP 梨뷀뵾?몄뿉寃???留욎뒿?덈떎." },
  "Runaan's Hurricane": { category: "Marksman", summary: "?ㅼ닔 ???吏???붾젰???꾩슂???먮뵜?먭쾶 留ㅼ슦 醫뗭뒿?덈떎." },
  "Rylai's Crystal Scepter": { category: "Mage", summary: "吏???쇳빐??愿묒뿭 ?ㅽ궗怨?議고빀??異붾끂? 吏???μ븙??媛뺥솕?⑸땲??" },
  "Serpent's Fang": { category: "Assassin", summary: "?ㅻ뱶媛 留롮? 議고빀??鍮좊Ⅴ寃?臾대꼫?⑤┫ ???⑥쑉?곸엯?덈떎." },
  "Serylda's Grudge": { category: "Assassin", summary: "?ы궧怨??먮젮吏??④낵源뚯? ?몃┫ ???덈뒗 愿???꾩씠?쒖엯?덈떎." },
  "Staff of Flowing Water": { category: "Support", summary: "AP 罹먮━? ?좏떥 議고빀??媛뺥솕?섎뒗 ?몄콌??肄붿뼱?낅땲??" },
  "Stasis": { category: "Enchant", summary: "?ㅼ씠釉뚯? ?붿궡, 沅곴레湲??곌퀎瑜???踰??딆뼱?대뒗 媛??媛뺥븳 ?몄콌?몄엯?덈떎." },
  "Sterak's Gage": { category: "Fighter", summary: "洹쇱젒 ?쒕윭媛 吏꾩엯 ???곗?吏 ?딅룄濡?踰꾪?紐⑹씠 ?섏뼱以띾땲??" },
  "Sundered Sky": { category: "Fighter", summary: "吏㏃? ??뵜怨??좎??μ쓣 紐⑤몢 梨숆린?ㅻ뒗 AD 釉뚮（??먭쾶 醫뗭뒿?덈떎." },
  "Sunfire Aegis": { category: "Tank", summary: "?깆빱??湲곕낯 ?꾪닾?κ낵 ?⑥씠釉?泥섎━ ?λ젰???щ젮二쇰뒗 ???肄붿뼱?낅땲??" },
  "Terminus": { category: "Marksman", summary: "?섏씠釉뚮━??諛??⑦옕 ?쒕윭媛 ?꾩뿴???뱀씠????媛뺥빀?덈떎." },
  "The Collector": { category: "Marksman", summary: "以묐컲 ??뵜怨?泥섑삎 援ш컙??媛뺥솕???쒗룷瑜??щ┰?덈떎." },
  "Thornmail": { category: "Tank", summary: "?됲? 湲곕컲 議고빀怨??뚮났???꾩뿴 ?곷?濡??숈떆??媛移섍? ?쎈땲??" },
  "Trinity Force": { category: "Fighter", summary: "湲곕낯湲?援먰솚??諛섎났?섎뒗 釉뚮（?? ?ㅼ빱誘몄뀛??留뚮뒫 肄붿뼱?낅땲??" },
  "Veil": { category: "Enchant", summary: "以묒슂??CC???ы궧??誘몃━ 留됱븘?대뒗 蹂댄샇 ?몄콌?몄엯?덈떎." },
  "Warmog's Armor": { category: "Tank", summary: "泥대젰 湲곕컲 ?깆빱媛 援먯쟾 ???ъ젙鍮꾨? 諛섎났?섍린 醫뗭뒿?덈떎." },
  "Wit's End": { category: "Marksman", summary: "AP ?뺣컯??媛뺥븷 ???⑦옕 ?쒕윭媛 ?쒓낵 留덉?瑜?媛숈씠 梨숆만 ???덉뒿?덈떎." },
  "Youmuu's Ghostblade": { category: "Assassin", summary: "濡쒕컢怨?泥?吏꾩엯 ?띾룄媛 以묒슂??AD 梨뷀뵾?몄쓽 ???肄붿뼱?낅땲??" },
  "Zeke's Convergence": { category: "Support", summary: "?깆빱 ?쒗룷?곌? 援먯쟾 媛쒖떆? ?꾧뎔 ??利앺룺???④퍡 ?몃┫ ??醫뗭뒿?덈떎." }
};


const laneLabels = { Baron: "諛붾줎", Jungle: "?뺢?", Mid: "誘몃뱶", Dragon: "?쒕옒怨?, Support: "?쒗룷?? };
const roleLabels = { Fighter: "?꾩궗", Tank: "?깆빱", Mage: "硫붿씠吏", Assassin: "?붿궡??, Marksman: "?먮뵜", Support: "?쒗룷??, Enchanter: "?몄콌??, Catcher: "罹먯쿂", Specialist: "?ㅽ럹?쒕━?ㅽ듃" };
const difficultyLabels = { Easy: "?ъ?", Medium: "蹂댄넻", Hard: "?대젮?" };



const allReferencedItems = new Set([
  ...Object.keys(itemData),
  ...Object.values(archetypeProfiles).flatMap((profile) => [
    ...profile.coreItems,
    ...profile.situationalItems,
    ...profile.boots,
    ...profile.enchants,
  ]),
]);

function normalizeDamageTag(damageType) {
  if (damageType === 'AP') return 'magic';
  if (damageType === 'AD') return 'physical';
  return 'mixed';
}

function assetPath(folder, baseName, extension) {
  return .//.;
}

function normalizeChampion(seed) {
  const profile = archetypeProfiles[seed.archetype];
  const combinedTags = Array.from(new Set([...profile.baseTags, ...seed.tags, normalizeDamageTag(seed.damageType)]));
  return {
    ...seed,
    displayName: seed.name,
    image: assetPath('champions', seed.name, 'jpg'),
    tags: combinedTags,
    profileLabel: profile.label,
    coreItems: profile.coreItems,
    situationalItems: profile.situationalItems,
    boots: profile.boots,
    enchants: profile.enchants,
    strengths: profile.strengths,
    weaknesses: profile.weaknesses,
    laneTip: profile.laneTip,
    teamfightTip: profile.teamfightTip,
    runes: getRunesForArchetype(seed.archetype),
    spells: getSpellsForChampion(seed),
    flavor: ${seed.name}는  성향이 뚜렷한 챔피언으로, 에서 존재감을 드러냅니다.,
    tmi: ${seed.name}는 진입 타이밍과 조합 이해도에 따라 체감 성능이 크게 달라지는 챔피언입니다.,
  };
}

function normalizeItem(name) {
  return {
    name,
    displayName: name,
    image: assetPath('items', name, 'png'),
    ...(itemData[name] || { category: 'Etc', summary: '상황에 따라 선택할 수 있는 아이템입니다.' }),
  };
}

function getRunesForArchetype(archetype) {
  const map = {
    juggernaut: ['정복자', '잔혹', '최후의 일격', '불굴'],
    diver: ['정복자', '승전보', '거인 사냥꾼', '전략가'],
    warden: ['여진', '약점 노출', '충성심', '개척자'],
    guardian: ['여진', '약점 노출', '뼈 방패', '개척자'],
    assassin: ['감전', '돌발 일격', '사냥의 증표', '천상의 몸놀림'],
    burstMage: ['감전', '약점 노출', '최후의 일격', '마나순환 팔찌'],
    battlemage: ['정복자', '침착', '거인 사냥꾼', '마나순환 팔찌'],
    artillery: ['에어리', '약점 노출', '사냥의 증표', '마나순환 팔찌'],
    marksman: ['치명적 속도', '잔혹', '거인 사냥꾼', '흡혈의 맛'],
    utilityMarksman: ['치명적 속도', '약점 노출', '거인 사냥꾼', '영감'],
    pokeMarksman: ['정복자', '잔혹', '거인 사냥꾼', '영감'],
    hypercarry: ['치명적 속도', '잔혹', '거인 사냥꾼', '흡혈의 맛'],
    skirmisher: ['정복자', '승전보', '최후의 일격', '천상의 몸놀림'],
    skirmishMarksman: ['정복자', '잔혹', '거인 사냥꾼', '흡혈의 맛'],
    enchanter: ['소환: 에어리', '약점 노출', '충성심', '마나순환 팔찌'],
    catcher: ['빙결 강화', '약점 노출', '충성심', '개척자'],
    specialist: ['에어리', '약점 노출', '거인 사냥꾼', '영감'],
    marksmanAssassin: ['감전', '잔혹', '사냥의 증표', '천상의 몸놀림'],
    marksmanFighter: ['정복자', '승전보', '최후의 일격', '흡혈의 맛'],
  };
  return map[archetype] || ['정복자', '잔혹', '거인 사냥꾼', '영감'];
}

function getSpellsForChampion(seed) {
  if (seed.lanes.includes('Jungle')) return ['강타', '점멸'];
  if (seed.roles.includes('Support')) return ['점멸', '점화'];
  if (seed.tags.includes('burst')) return ['점멸', '점화'];
  return ['점멸', '보호막'];
}

const champions = championSeedData.map(normalizeChampion).sort((a, b) => a.displayName.localeCompare(b.displayName));
const championMap = Object.fromEntries(champions.map((champion) => [champion.displayName, champion]));
const itemMap = Object.fromEntries(Array.from(allReferencedItems).map((name) => [name, normalizeItem(name)]));

window.WildriftData = {
  champions,
  championMap,
  itemMap,
  laneLabels,
  roleLabels,
  difficultyLabels,
  recommendationRules,
};
